Update zsh prompt for Linux

diff --git a/zsh_functions b/zsh_functions
--- a/zsh_functions
+++ b/zsh_functions
@@ -14,6 +14,26 @@ up() {
     fi
 }
 
+ps1_prompt() {
+    # Remember if the last command exited successfully.
+    last_command_status=$?
+
+    if [ "$USER" = "root" ]; then
+        color="blue"
+        prompt="#"
+    else
+        color="red"
+        prompt="♥"
+    fi
+
+    # Override the color to black if the last command failed.
+    if [ $last_command_status -ne 0 ]; then
+        color="black"
+    fi
+
+    echo "%F{$color}$prompt%f"
+}
+
 git_prompt() {
     # Use the first line of git status
     git_status=$(git status --long 2> /dev/null | head -n 1 | sed 's/On branch //g')
